export default {
  overviewPanelWidth: 300,
  detailsPanelWidth: 700,
  overviewTitleXPosition: 10,
  detailsTitleXPosition: 310,
  panelTitleYPosition: 15,
  panelTitleHeight: 55,
  backboneXPosition: 240,
  viewboxHeight: 440,
  trackWidth: 20,
  dataTrackWidth: 10,
  overviewTrackYPosition: 70,
  trackLabelYPosition: 25,
  trackMapLabelYPosition: 35,
  selectedBackboneXPosition: 320,
  navigationButtonHeight: 15,
};