export default {
  overviewPanelWidth: 300,
  detailsPanelWidth: 700,
  overviewTitleXPosition: 10,
  detailsTitleXPosition: 310,
  panelTitleYPosition: 15,
  panelTitleHeight: 40,
  backboneXPosition: 230,
  viewboxHeight: 440,
  trackWidth: 20,
  trackYPosition: 60,
  trackLabelYPosition: 25,
  trackMapLabelYPosition: 35,
  selectedBackboneXPosition: 320,
};